### ISSUE TITLE
Splitting out RNA-seq lesson

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/rnaseq-data-analysis#1]
As discussed in datacarpentry/datacarpentry#117 we in the process of splitting the main lessons repo into a bunch of smaller component repos. This is my attempt at extracting the history for the RNA-seq lesson plus the standard helper files

@stephenturner can you check and make sure this looks good to you, and if it does go ahead and close this. Thanks.

**Comment by stephenturner** [comment]
looks good!

**Comment by ethanwhite** [comment]
Thanks @stephenturner!
